# AppVeyor CI configuration

version: "#{build} ({branch})"

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      PREMAKE_ACTION: vs2022

configuration:
  - Debug
  - Release

platform: Win32

install:
  - ps: |
      Write-Host "Updating version information..." -ForegroundColor Cyan

      Update-AppveyorBuild -Version $(& tools/premake5.exe version | select -Last 1)
  - git submodule update --init --recursive
  - ps: |
      Write-Host "Generating project files with premake..." -ForegroundColor Cyan
      & "./tools/premake5.exe" $env:PREMAKE_ACTION
      Write-Host "Generated" -ForegroundColor Green

build:
  project: build/iw4x.sln
  parallel: true
  verbosity: minimal

artifacts:
  - path: build/bin/**/*.dll
  - path: build/bin/**/*.pdb
